name: ci/cd-aws
on:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup environment and test security
        run: make all
